---
- name: Copy drush makefile into place.
  copy:
    src: "{{ drush_makefile_path }}"
    dest: /tmp/drupal.make.yml
  when: drupal_site.stat.exists == false

- name: Ensure drupal_core_path directory exists.
  file:
    path: "{{ drupal_core_path }}"
    state: directory
    recurse: yes
    mode: 0775
  when: drupal_site.stat.exists == false

- name: Ensure drupal_core_path directory is owned by ssh user.
  file:
    path: "{{ drupal_core_path }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0775
  when: drupal_site.stat.exists == false

- name: Generate Drupal site with drush makefile.
  command: >
    {{ drush_path }} make -y /tmp/drupal.make.yml --no-gitinfofile
    chdir={{ drupal_core_path }}
  when: drupal_site.stat.exists == false
  become: no
